services:
  postgres:
    image: postgres
    container_name: dev-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 151919
      POSTGRES_DB: bingo
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: backend-dev
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgres://postgres:151919@postgres:5432/bingo

volumes:
  pgdata:
